name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
      env:
        DOTNET_NOLOGO: 1
    - run: dotnet test
    - name: Build and publish
      run: dotnet publish AuroraLoader --no-restore --self-contained true -f netcoreapp3.1 -r win-x86 -o ./Release -p:PublishReadyToRun=true -p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./Release/*
    - uses: actions/upload-artifact@v2
      with:
        path: ./README.md
    - uses: actions/upload-artifact@v2
      with:
        path: ./CHANGELOG.md
